Repository tm21cy/Bit, pull requests merged in 2023-01, with the labels that each got.

#9 docs: add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#12 General fixes
  package.json
  pnpm-lock.yaml
  src/commands/418.ts
  src/commands/dev.ts
  src/commands/ping.ts
  src/commands/profile.ts
  src/commands/template.dev
  src/enums/colors.ts
  src/routes/Notifications.ts
  src/routes/Profiles.ts
  src/routes/Query.ts
  src/services/boot.ts
  src/utilities/general.ts
Labels: enhancement

#21 V2.1 WIP MVP
  index.d.ts
  package.json
  pnpm-lock.yaml
  src/buttons/join.ts
  src/buttons/leave.ts
  src/commands/helper-roles.ts
  src/commands/management.ts
  src/commands/moderation.ts
  src/commands/tag.ts
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/guildMemberUpdate.ts
  src/events/interactionCreate.ts
  src/events/interactionHandler.ts
  src/events/presenceUpdate.ts
  src/index.ts
  src/routes/HelpRoles.ts
  src/routes/JoinAlerts.ts
  src/routes/LikeUsers.ts
  src/services/normalizer.ts
  src/services/sentry.ts
  src/types/Apis.ts
  src/types/DatabaseSchemas.ts
  src/types/Interfaces.ts
  src/types/help-roles.ts
Labels: enhancement, high priority, semver: minor

#23 features: list and scan
  .env.example
  package.json
  pnpm-lock.yaml
  src/commands/dev.ts
  src/commands/management.ts
  src/commands/moderation.ts
  src/commands/tag.ts
  src/services/sentry.ts
  src/types/applicationNotifications.ts
Labels: enhancement, medium priority

#24 feat/auto-detect-lang
  .env.example
  src/events/messageCreate.ts
  src/index.ts
  src/services/logger.ts
Labels: medium priority

#28 Profile/Helper Backend Caching Update
  .gitignore
  package.json
  pnpm-lock.yaml
  src/cache/Cache.ts
  src/cache/CacheEnums.ts
  src/events/ready.ts
  src/index.ts
  src/routes/Comments.ts
  src/routes/HelpRoles.ts
  src/routes/LikeUsers.ts
  src/routes/Notifications.ts
  src/routes/Profiles.ts
  src/types/Interfaces.ts
Labels: enhancement, high priority

#33 docs: new readme and contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation, low priority

#34 Pre-Canary Part 1
  src/buttons/notif.ts
  src/commands/notifications.ts
  src/commands/profile.ts
  src/commands/thank.ts
  src/dal/Notification.ts
  src/dal/Profile.ts
  src/menus/menu.ts
  src/menus/notifs.ts
  src/menus/searchres.ts
  src/models/Notification.ts
  src/models/Profile.ts
  src/routes/Notifications.ts
  src/routes/Profiles.ts
  src/services/api/ProfileService.ts
  src/utilities/profiles/ProfileBuilder.ts
  src/utilities/profiles/render.ts
Labels: enhancement, high priority

#35 Pre-Canary Part 2
  package.json
  pnpm-lock.yaml
  src/dal/JoinAlert.ts
  src/dal/types/JoinAlertDALFilters.ts
  src/express/routes/status.routes.ts
  src/index.ts
  src/models/JoinAlert.ts
  src/routes/JoinAlerts.ts
  src/routes/Query.ts
  src/services/api/JoinAlertService.ts
Labels: enhancement, medium priority

#36 Feat/join-alerts
  .env.example
  package.json
  pnpm-lock.yaml
  src/commands/helper-roles.ts
  src/commands/management.ts
  src/commands/moderation.ts
  src/commands/profile.ts
  src/events/guildMemberAdd.ts
  src/events/messageCreate.ts
  src/index.ts
  src/routes/Query.ts
  src/services/sentry.ts
  src/types/Apis.ts
  src/types/Interfaces.ts
Labels: enhancement, high priority, semver: major
